config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback' , to: 'sessions#create'

  resources :genres , :users
  resources :videos do
    resources :reviews
  end

  get 'login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  root 'application#home'

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_and_belongs_to_many :videos

    validates :title, presence: true, uniqueness: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    before_action :authentication_required, :authorize_admin
    before_action :set_genre, only: [:show, :edit, :update, :destroy]
    
    def index
        @genres = Genre.all
    end

    def show
    end

    def new
        @genre = Genre.new
    end

    def create
        @genre = Genre.new(genre_params)
        if @genre.save
            redirect_to @genre
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @genre.update(genre_params)
            redirect_to @genre
        else
            render :edit
        end
    end

    def destroy
        @genre.destroy
        redirect_to genres_path
    end

    private

    def genre_params
        params.require(:genre).permit(:title)
    end

    def set_genre
        @genre = Genre.find(params[:id])
    end
    
end

app/helpers/genres_helper.rb
module GenresHelper
    def genres_count
        Genre.count
    end
end

app/views/genres/_form.html.erb
<% if genre.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% genre.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: genre, local: true do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => 'form-control' %><br><br>
  
    <%= f.submit %>  
<% end %>

app/views/genres/_genre.html.erb
<%= genre.title %><br>

app/views/genres/edit.html.erb
<h1>Edit Genre</h1>

<%= render "form", genre: @genre %>

<%= link_to 'Back', genre_path(@genre) %>

app/views/genres/index.html.erb
<h1>Genres</h1>
<%= link_to 'New Genre', new_genre_path %><br><br>
<ul>
  <% @genres.each do |genre| %>
    <li>
        <%= link_to genre.title, genre %> 
    </li>
  <% end %>
</ul>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<% if @genre.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @genre.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @genre, local: true do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>
  </div>

  <div>
    <%= f.submit %>  
  </div>
<% end %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<h1><%= render @genre %></h1>

<%= link_to 'Back', genres_path %>

<ul>
  <li><%= link_to 'Edit Genre', edit_genre_path(@genre) %></li>
  <li><%= link_to "Delete Genre", genre_path(@genre),
                method: :delete,
                data: { confirm: "Are you sure?" } %></li>
</ul>

<h2>Videos</h2>
<%= render @genre.videos %>