config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback' , to: 'sessions#create'

  resources :genres , :users
  resources :videos do
    resources :reviews
  end

  get 'login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  root 'application#home'

end

app/models/video.rb
class Video < ApplicationRecord
    has_and_belongs_to_many :genres
    has_many :reviews, dependent: :destroy
    has_many :users, through: :reviews

    accepts_nested_attributes_for :genres, reject_if: :all_blank

    validates :released_year, numericality: { only_integer: true }, allow_nil: true, length: { is: 4}
    validates :title, presence: true, uniqueness: true

    scope :new_released, -> {where("released_year >= ?", Time.current.year) }

    def rating_to_stars
        self.reviews.average('rating')
    end

    def self.search(genre,is_new_released)
        if is_new_released == "1"
            Video.new_released
        elsif !genre || genre[:genre_id].empty? 
           all
        else
            Genre.find(genre[:genre_id]).videos
        end
    end 
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

    before_action :authentication_required
    before_action :authorize_admin, except: [:index, :show]
    before_action :set_video, only: [:show, :edit, :update]
    
    def index
        @videos = Video.search(params[:genre],params[:new_released])
        if @videos.empty?
            flash.now[:notice] = "There is no video for selected genre!"
        end
    end 

    def show
    end

    def new
        @video = Video.new
        build_new_genres
    end
    
    def create
        @video = Video.new(video_params)
        if @video.save
            redirect_to video_path(@video)
        else
            build_new_genres
            render :new
        end
    end

    def edit
    end

    def update
        if @video.update(video_params)
            redirect_to @video
        else
            render :edit
        end
    end

    def destroy
        @video = Video.find(params[:id])
        @video.destroy
        redirect_to videos_path
    end

    private

    def video_params
        params[:video][:image_url] = "videos/" + params[:video][:image_url].original_filename if params[:video][:image_url]
        params.require(:video).permit(:title, :description, :image_url, :released_year, genre_ids: [], genres_attributes: [:title])
    end

    def set_video
        @video = Video.find(params[:id])
    end

    def build_new_genres
        2.times { @video.genres.build }
    end

end

app/helpers/videos_helper.rb
module VideosHelper

    def render_stars(value)
        output = ''
        if (1..5).include?(value.to_i)
          value.to_i.times { output += '*'}
        end
        output
      end

    def videos_count
        Video.count
    end

    def five_videos
      Video.limit(5).order("RANDOM()")
    end
      
end

app/views/videos/_form.html.erb
<% if video.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% video.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: video, local: true do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => 'form-control'  %>
    </p>
    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => 'form-control'  %>
    </p>
    <p>
      <%= f.label :released_year %><br>
      <%= f.text_field :released_year, :class => 'form-control'  %>
   </p>
    <p>
      <%= f.label :image_url %>
      <%= f.file_field :image_url%>
    </p>
    <div class="checkbox_container">
      <%= f.collection_check_boxes :genre_ids, Genre.order(:title), :id, :title, include_hidden: false do |b| %>
        <div>
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
    </div>

    <% if video.id == nil %>
      <p>
        New Genres:
        <ul>
        <%= f.fields_for :genres do |genres_form| %>
          <li>
                <%= genres_form.label :title %>
                <%= genres_form.text_field :title %>
            </li>
          <% end %>
        </ul>
      </p>
    <% end %>

    <p>
      <%= f.submit %>
    </p>
  <% end %>

app/views/videos/_video.html.erb
<br>
<strong>Title:</strong><%= video.title %><br>

<strong>Description:</strong><%= video.description %><br>

<strong>Released Year:</strong><%= video.released_year %><br><br>

<% if video.image_url %>
    <%= image_tag video.image_url, class: "video_image"  %><br><br>
<% end %>

app/views/videos/edit.html.erb
<h1>Edit Video</h1>
<%= link_to 'Back', video_path(@video) %>
<%= render "form", video: @video %>

app/views/videos/index.html.erb
<h1>Videos</h1>
<%= link_to 'New Video', new_video_path %><br><br>

<%= form_with(url: '/videos', method: 'get', local: true) do |f| %>
  <%= collection_select :genre, :genre_id, Genre.order(:title), :id, :title, :prompt => 'Genres' %>
  <%= f.check_box :new_released %>
  <%= f.label :new_released, "New Released" %><br>
  <%= f.submit "Search", :class => "btn btn-info" %>
<% end %>

<br><br>
<ul>
  <% @videos.each do |video| %>
    <li>
        <%= link_to video.title, video %> 
    </li>
  <% end %>
</ul>

  

app/views/videos/new.html.erb
<h2>New Video</h2>
<%= link_to 'Back', videos_path %>
<%= render 'form', video: @video %>

app/views/videos/show.html.erb
<%= link_to 'Back', videos_path %><br>

<ul>
  <li><%= link_to 'Edit Video', edit_video_path(@video) %></li>
  <li><%= link_to "Delete Video", video_path(@video),
                method: :delete,
                data: { confirm: "Are you sure?" } %></li>
</ul>

<%= render @video %>

<h3>Video's Genres</h3>
<%= render @video.genres %><br>

<div id="star-rating">
  <% if @video.rating_to_stars.blank? %>
    <%= link_to 'Please add a Review', new_video_review_path(@video) %>
  <% else %>
    Rating: <%=link_to render_stars(@video.rating_to_stars), video_reviews_path(@video) %>
  <% end %>
</div> 