config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback' , to: 'sessions#create'

  resources :genres , :users
  resources :videos do
    resources :reviews
  end

  get 'login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  root 'application#home'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authentication_required
    before_action :set_review, only: [:show, :edit, :update, :destroy]
    
    def index
        @video = Video.find(params[:video_id])
        @reviews = @video.reviews
    end

    def show
    end

    def new
        @review = Review.new(video_id: params[:video_id], user_id: current_user.id)
    end

    def create
        @review = Review.new(review_params)
        if @review.save
            redirect_to video_path(@review.video)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @review.update(review_params)
            redirect_to video_reviews_path(@review.video)
        else
            render :edit
        end
    end

    def destroy
        @review.destroy
        redirect_to video_reviews_path(@review.video)
    end

    private

    def review_params
        params.require(:review).permit(:rating, :user_id, :video_id, :description)
    end

    def set_review
        @review = Review.find(params[:id])
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
    def user_video_exists?(video)
        Review.exists?(:user_id => current_user.id, :video_id => video.id)
    end

    def review_by_user_video(video)
        Review.where(:user_id => current_user.id, :video_id => video.id).first
    end

end

app/views/reviews/_form.html.erb
<% if review.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: [ review.video, review ], local: true do |f| %>
    <p>
      <%= f.label :rating %><br>
      <%= f.text_field :rating, :class => 'form-control'  %>
    </p>
    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => 'form-control'  %>
    </p>
    <p>
        <%= f.hidden_field :video_id  %>
        <%= f.hidden_field :user_id %>
    </p>
    <p>
      <%= f.submit %>
    </p>

  <% end %>

app/views/reviews/edit.html.erb
<h2>Edit Review for <%= @review.video_name %></h2>
<%= render 'form', review: @review %>
<%= link_to 'Back', video_path(@review.video) %>

  

app/views/reviews/index.html.erb
<h2><%= @video.title %> Reviews</h2>

<%= link_to 'Back', video_path(@video) %> | 
<% if user_video_exists?(@video) %>
    <%=link_to 'Edit review', edit_video_review_path(@video.id, review_by_user_video(@video)) %> | 
    <%= link_to "Delete review", video_review_path(@video, review_by_user_video(@video)),
                method: :delete,
                data: { confirm: "Are you sure?" } %><br><br>
<% else %>
    <%=link_to 'Write a review', new_video_review_path(@video.id) %><br>
<% end %>

<% @reviews.each do |review| %>
    <strong>Review By: <%= review.user_name %> </strong><br>
    <strong>Rating: <%= render_stars(review.rating) %> </strong><br>
    <strong>Description: <%= review.description %> </strong><br><br>
<% end %>

app/views/reviews/new.html.erb
<h2>Add a Review for <%= @review.video_name %></h2>

<% if @review.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: [ @review.video, @review ], local: true do |f| %>
    <p>
      <%= f.label :rating %><br>
      <%= f.text_field :rating, :class => 'form-control'  %>
    </p>
    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => 'form-control'  %>
    </p>
    <p>
      <%= f.submit %>
    </p>

  <% end %>

  <%= link_to 'Back', video_path(@review.video) %>

  