config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback' , to: 'sessions#create'

  resources :genres , :users
  resources :videos do
    resources :reviews
  end

  get 'login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  root 'application#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFlix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
  </head>

  <body>
  <nav class="navbar fixed-top navbar-expand-lg  navbar-gray bg-dark">
    <a class="navbar-brand" href="<%= root_path %>">MyFlix</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <% if !current_user %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_path %>"/> Sign Up <span class="sr-only">(current)</span></a>  
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= login_path %>"/> Log in <span class="sr-only">(current)</span></a>  
        </li>
      <% else %>
         <li class="nav-item">
            <a class="nav-link" href="<%= user_path(current_user) %>"/> <%= current_user.name if current_user %> <span class="sr-only">(current)</span></a>  
          </li>
        <% if !is_admin? %>
          <li class="nav-item">
          <a class="nav-link" href="<%= videos_path %>"/> Videos <span class="sr-only">(current)</span></a>  
          </li>
        <% end %>
        <li class="nav-item">
         <a class="nav-link" href="<%= logout_path %>"/> Log out <span class="sr-only">(current)</span></a>  
        </li>
      <% end %>
      </ul>
      
    </div>
  </nav>
  <div class="container"  role="main" >
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
      <%= yield %>
  </div>
  
  </body>
  
</html>